var miembro = {
    "idMiembro": 0,
    "primerApellido": "",
    "nombre": "",
    "email": "",
    "password": ""
};

var premio = {
    "idPremio": 0,
    "titulo": "",
    "descripcion": "",
    "puntos": 0,
    "desdeFecha": new Date(),
    "hastaFecha": new Date(),
    "stockInicial": 10
}

var llamada = {
    "fecha": new Date(),
    "hora": new Date(),
    "codoscio": 0,
    "numeruve": 0,
    "codclien": 0,
    "codusuar": 0,
    "nomclien": 0,
    "dirllama": "",
    "numllama": "",
    "puerllama": "",
    "ciudadre": "",
    "tipservi": 0,
    "telefono": "",
    "observac2": "",
    "codautor": "",
    "observa1": "",
    "licencia": "",
    "matricul": "",
    "idservic": "",
    "opereser": "",
    "opedespa": "",
    "estado": "",
    "observa2": "",
    "fecreser": new Date(),
    "horreser": new Date(),
    "fecaviso": new Date(),
    "horaviso": new Date(),
    "fecllega": new Date(),
    "horllega": new Date(),
    "fecocupa": new Date(),
    "horocupa": new Date(),
    "fecfinal": new Date(),
    "horfinal": new Date(),
    "importtx": 0.0,
    "impcompr": 0.0,
    "extcompr": 0.0,
    "impventa": 0.0,
    "extventa": 0.0,
    "distanci": 0.0,
    "suplemen": 0.0,
    "imppeaje": 0.0,
    "imppropi": 0.0,
    "facturad": 0.0,
    "abonados": 0,
    "validado": 0,
    "liquidasocio": 0,
    "facturadocliente": 0,
    "centrovip": "",
    "dnivip": "",
    "npvip": "",
    "tpoespera": 0.0,
    "impdistanci": 0.0,
    "impespera": 0.0
}

var canje = {
    "idCanje": 0,
    "fecha": new Date(),
    "idMiembro": 0,
    "idPremio": 0,
    "unidades": 0,
    "puntos": 0
}